server:
    port: 8080
spring:
    datasource:
        password: 123456
        url: jdbc:postgresql://localhost:5432/shoe-shop?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
cloudinary:
    cloud-name : ${CLOUD_NAME:thangdevcloud}
    api-key : ${API_KEY:623649172437435}
    api-secret : ${API_SECRET:xxWNNj0cDxMCqnI-V71d0ZppPRg}

app:
    jwt-secret-key: provip123
    jwt-expiration: 604800000