server:
    port: 8080
spring:
    datasource:
        password: 1234
        url: jdbc:mysql://localhost:3306/garden
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
cloudinary:
    cloud-name : ${CLOUD_NAME}
    api-key : ${API_KEY}
    api-secret : ${API_SECRET}