server:
    port: 8080
spring:
    datasource:
        password: 1234
        url: jdbc:mysql://localhost:3306/garden
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
cloudinary:
    cloud-name : ${CLOUD_NAME:thangdevcloud}
    api-key : ${API_KEY:623649172437435}
    api-secret : ${API_SECRET:xxWNNj0cDxMCqnI-V71d0ZppPRg}